csvDBConfig: &csvDBConfig
  code: csvdb
  connectionString: "phone_number.csv"
useCaseConfig:
  listFirstActivationDates:
    code: listFirstActivationDates
    phoneRepoConfig: &phoneRepoConfig
      code: phoneRepo
      dataStoreConfig: *csvDBConfig